# -*- coding: utf-8 -*-
"""valentine_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydKmOerx6OY6I5UtpAeocrAd_jUG4lye
"""


import streamlit as st
import random

# Set page config for a clean look
st.set_page_config(page_title="Strategic Proposal FY2026", page_icon="📈")

# Initialize session state for the "No" counter
if 'no_count' not in st.session_state:
    st.session_state.no_count = 0
if 'accepted' not in st.session_state:
    st.session_state.accepted = False

# Layout
st.title("Final Term Sheet: Strategic Partnership")
st.subheader("To: My Favourite Asset")

if not st.session_state.accepted:
    st.write("### Will you be my Valentine?")

    # Calculate button sizes based on how many times she hit "No"
    yes_size = 1.0 + (st.session_state.no_count * 0.5)  # Grows significantly
    no_size = max(0.1, 1.0 - (st.session_state.no_count * 0.2))  # Shrinks toward zero

    col1, col2 = st.columns([yes_size, no_size])

    with col1:
        if st.button("YES", type="primary", use_container_width=True):
            st.session_state.accepted = True
            st.rerun()

    with col2:
        # If "No" is clicked, increment counter and trigger the "Please" loop
        if st.button("No", type="secondary", use_container_width=True):
            st.session_state.no_count += 1
            st.rerun()

    # The "Please" logic from your video
    if st.session_state.no_count > 0:
        pleading_messages = [
            "Please? 🥺",
            "Are you sure? Financial markets are volatile!",
            "Think about the ROI...",
            "Transaction declined. Try clicking 'Yes' instead.",
            "I'll buy you nuggets? 🍟",
            "Don't break the hedge!",
        ]
        # Display a message based on count or random
        msg_index = min(st.session_state.no_count - 1, len(pleading_messages) - 1)
        st.error(pleading_messages[msg_index])

else:
    # Success State
    st.balloons()
    st.success("## TRANSACTION CONFIRMED! ✅")
    st.write("You have successfully merged with the Ikhwan Portfolio. See you on Feb 14th.")
    st.image("https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJqZndqZndqZndqZndqZndqZndqZndqZndqZndqZndqZndqJmVwPXYxX2ludGVybmFsX2dpZl9ieV9pZCZjdD1n/kyLYXonQpw60WODdVz/giphy.gif")
